### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by AlexanderKolesnikovSaritasa** [GetStream/stream-chat-android-livedata#18]
SDK 4.2.11-beta-5

When the users join/leave channels, sometimes I retrieve the next crash:

![image](https://user-images.githubusercontent.com/58584469/87950886-14417b00-cad2-11ea-8f17-951cdba6b7c4.png)

It is not reproduced always, but rather often.

I saw the source code, and I think that using the "!!" operator is a bad idea, that can lead the project to crashes because it does not guarantee that variables are not null. I think you should do refactor these places. Thank you.

gz#4521

**Comment by tbarbugli** [comment]
@AlexanderKolesnikovSaritasa thank you for reporting this, do you happen to have a copy of your logs? the NPE is happening while handling a WS event, it would be super useful to see which event it is (if you have logging enabled you should see a JSON encoded payload before the last stacktrace)

**Comment by AlexanderKolesnikovSaritasa** [comment]
@tbarbugli Thank you for your answer. Unfortunately, I haven't any more logs now.
Sure, these logs can be super useful, but as I think there is the exactly bad practice - using the !! operator that leads to crashes.

**Comment by tschellenbach** [comment]
JC is working on a fix for this and other event typing related issues: https://github.com/GetStream/stream-chat-android-client/pull/55
