### ISSUE TITLE
launcher icons in resources

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android-livedata#2]
The aar file contains launcher icons in resources 
![image](https://user-images.githubusercontent.com/837498/81033586-5b9a7100-8ebe-11ea-8a21-5776f8dbb940.png)
It causes conflict with application icons.
I think icons should be deleted from aar

**Comment by tschellenbach** [comment]
Thanks for spotting that, will remove it in the next release

**Comment by tschellenbach** [comment]
fixed in 0.3.4, thanks for reporting this.
