### ISSUE TITLE
Incorrect work of QuerySort

### ISSUE THREAD

**Issue by AlexanderKolesnikovSaritasa** [GetStream/stream-chat-android-livedata#21]
SDK 4.2.10-beta

I just created a screen with channels and use the next code:
```
    val filter = Filters.and(Filters.`in`("members", userId))
    val querySort = QuerySort().desc("last_message_at")
    channelsViewModel?.setQuery(filter, querySort)
```
As a result, I got all necessary channels but with unexpected sorting.

**Comment by JcMinarro** [comment]
Hello @AlexanderKolesnikovSaritasa 
New version has been release that contains the improvement done into our Stream-Livedata SDK, and should be fixed it now.
Could you use the version 4.2.11-beta-7 and check if it is working fine to you now?

**Comment by JcMinarro** [comment]
Hello @AlexanderKolesnikovSaritasa 
Local Query Sort has been completed supported on the [last version](https://github.com/GetStream/stream-chat-android/releases/latest) of the SDK
