### ISSUE TITLE
Question about the Room InMemoryDatabase usage

### ISSUE THREAD

**Issue by VGJohn** [GetStream/stream-chat-android-livedata#3]
From my understanding if you don't enable offline storage in `ChatDomainImpl` then Room's `InMemoryDatabase` is used to keep data synchronised including when the user potentially goes offline while using an app. How are you ensuring that messages, reactions, etc. performed while the user has no connection are persisted across process death? 

According to the [`InMemoryDatabase` documentation](https://developer.android.com/reference/androidx/room/Room#inMemoryDatabaseBuilder(android.content.Context,%20java.lang.Class%3CT%3E)) it gets destroyed when the process is killed. So there is a potential scenario where those messages, reactions, etc. performed offline aren't synced when resuming from process death. And of course the entire database needs to be reconstructed and resynced. 

I've only been look at the source for less than an hour, so you may have a fail safe for that scenario already but just wanted to get some clarification on how that's handled.

**Comment by tschellenbach** [comment]
I'm not quite sure I understand your use case. You want to disable offline storage but still have the data recover when resuming the process?

In other words, why not just enable offline storage?

**Comment by VGJohn** [comment]
That's fair, so is the InMemoryDatabase more useful for testing purposes? I'm guessing I could use if it for integration tests.

**Comment by tschellenbach** [comment]
If you disable offline you basically just get the conversion from a stream of events to livedata objects. Which is still easier to work with (ie you have a messages livedata objects) vs having to parse a couple dozen events.
