### ISSUE TITLE
Missing use cases

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android-livedata#4]
- get message
- get messages
- get user
- get users

Getting messages with `domain.useCases.queryChannels` is not intuitive at all.
@tschellenbach thoughts?

**Comment by tschellenbach** [comment]
Usually when you're building chat you want to display a channel with a list of messages or a list of channels. What's the use case for getting individual users or messages? Do you have a design of what the customer is building?

**Comment by elevenetc** [comment]
I'm more about api clarity. Messages screen contains messages firstly and then might need channel or might not need:
```kotlin
class ChatFragment(val cid:String): Fragment {
  fun onCreate() {
    val messagesAdapter = MessagesAdapter()
    
    chat.getMessages(cid, limit, offset).enqueue { -> channel, messages
      title = channel.name
      messagesAdapter.setMessages(messages)
    }
  }
}
```
And it's common perception of repository/data layer. It should return data and not guess how it's used. Although still can provide convenience methods apart data getters.

**Comment by tschellenbach** [comment]
At the repository level we have this available, i'm not exposing it right now. The idea of only getting messages doesn't map well with how our API retrieves data for a channel.

**Comment by elevenetc** [comment]
Well, nobody cares how API works at this level. It's an opportunity make api easier. 
I'm trying to retrieve first 10 messages and still not sure what's wrong, there is no messages:
```
chat.domain.useCases.queryChannels.invoke(Filters.eq("cid", "messaging:x-test"), limit = 1, messageLimit = 10).enqueue {
}
```
Might be that `queryChannels` creates new channel with no message. But `getMessages` strictly would return error if there is no channel. All hidden magic behind api make it harder to integrate.
